import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "Herveg",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen justify-between overflow-x-hidden">
        {/* <header /> */}
        <div>
          <NavBar />
        </div>
        {/* main section */}
        <div className="grow">{children}</div>

        {/* footer section */}
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
