import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Herveg",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen justify-between overflow-x-hidden">
        {/* <header /> */}
        <div>
          <NavBar />
        </div>
        {/* main section */}
        <div>{children}</div>

        {/* footer section */}
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
